### ISSUE TITLE
iverilog gives no warning against dangling wires within a module

### ISSUE THREAD

**Issue by dword1511** [steveicarus/iverilog#24]
For the latest git version, the following code with a dangling wire "e" in the "bug2" module

module bug2 (input a, input b, input c, output d);
  wire e;
  assign d = c & e;
endmodule

module top ();
  wire mon;
  bug2 inst (.a(1'b1), .b(1'b1), .d(mon));
endmodule

produces no warning about "e" even if -Wall is turned on. iverilog does give warning about the dangling "c" in the port during instantiation.

It will also be helpful if iverilog can check unused wires and regs. This will be helpful for removing logics that are no longer needed in a huge complicated design.

**Comment by gdraps** [comment]
For linting, check out --lint-only on verilator [1], which provides the following feedback on bug2.v, and is configurable.

    $ verilator --lint-only -Wall bug2.v 
    %Warning-UNUSED: bug2.v:2: Signal is not used: a
    %Warning-UNUSED: Use "/* verilator lint_off UNUSED */" and lint_on around source to disable this message.
    %Warning-UNUSED: bug2.v:2: Signal is not used: b
    %Warning-UNDRIVEN: bug2.v:3: Signal is not driven: e
    %Error: Exiting due to 3 warning(s)
    %Error: Command Failed /usr/bin/verilator_bin --lint-only -Wall bug2.v

[1] http://www.veripool.org/wiki/verilator

**Comment by steveicarus** [comment]
I actually have an idea how to tackle this, so I'll take a crack at it.

**Comment by steveicarus** [comment]
I've pushed into git master support for the -Wfloating-nets flag, which does pretty much exactly what is requested here.

**Comment by ahogen** [comment]
It seems this flag doesn't exist anymore in v10.2 (I haven't looked at older versions)

See: https://github.com/steveicarus/iverilog/blob/v10_2/driver/main.c#L495-L586

Can I ask what happened to this feature?

**Comment by ahogen** [comment]
This support was added in commit https://github.com/steveicarus/iverilog/commit/8f095f12de2d6bec34f0fda076bb1f108262ee4f. This feature never made it to v10.2 (I haven't looked at older versions)

See: https://github.com/steveicarus/iverilog/blob/v10_2/driver/main.c#L495-L586

Can I ask what happened to this feature? Seems useful and (was) listed on the Wiki, so it appeared to be a feature available in the latest release.

**Comment by ahogen** [comment]
Ah okay. That makes more sense. Apologies for my failure to read the Wiki correctly/thoroughly.

Not that it matters, but it sure seems like there is a 10.2 release. I see it both here on Github and in the FTP server. Maybe this is an "unreleased" release?

Thanks again for your clarification on the `-Wfloating-nets` option. I'll try it out in [master](https://github.com/steveicarus/iverilog/tree/master/).

**Comment by martinwhitaker** [comment]
Steve's never announced 10.2 as an official release. I did ask about this on the iverilog-devel mailing list a while back, but didn't get a reply. SourceForge is even more behind - it still shows 10.0 as the latest.
